In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

torch.manual_seed(1)

In [2]:
lstm = nn.LSTM(3, 3)  # Input dim is 3, output dim is 3
inputs = [torch.randn(1, 3) for _ in range(5)]  # make a sequence of length 5

# initialize the hidden state.
hidden = (torch.randn(1, 1, 3),
          torch.randn(1, 1, 3))
for i in inputs:
    # Step through the sequence one element at a time.
    # after each step, hidden contains the hidden state.
    out, hidden = lstm(i.view(1, 1, -1), hidden)

# alternatively, we can do the entire sequence all at once.
# the first value returned by LSTM is all of the hidden states throughout
# the sequence. the second is just the most recent hidden state
# (compare the last slice of "out" with "hidden" below, they are the same)
# The reason for this is that:
# "out" will give you access to all hidden states in the sequence
# "hidden" will allow you to continue the sequence and backpropagate,
# by passing it as an argument  to the lstm at a later time
# Add the extra 2nd dimension
inputs = torch.cat(inputs).view(len(inputs), 1, -1)
hidden = (torch.randn(1, 1, 3), torch.randn(1, 1, 3))  # clean out hidden state
out, hidden = lstm(inputs, hidden)
print(out)

print(hidden)

tensor([[[-0.0187,  0.1713, -0.2944]],

        [[-0.3521,  0.1026, -0.2971]],

        [[-0.3191,  0.0781, -0.1957]],

        [[-0.1634,  0.0941, -0.1637]],

        [[-0.3368,  0.0959, -0.0538]]], grad_fn=<StackBackward>)
(tensor([[[-0.3368,  0.0959, -0.0538]]], grad_fn=<StackBackward>), tensor([[[-0.9825,  0.4715, -0.0633]]], grad_fn=<StackBackward>))


In [20]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

torch.manual_seed(1)
n_aa = 21 
n_tokens = n_aa + 2
embedding_dim = 64
lstm_hidden_dim = 128
embed = torch.nn.Embedding(n_tokens, embedding_dim)
lstm = nn.LSTM(input_size=embedding_dim, hidden_size=lstm_hidden_dim, num_layers=2, batch_first=True)

def train_model(model, epochs=10, lr=0.001):
    parameters = filter(lambda p: p.requires_grad, model.parameters())
    optimizer = torch.optim.Adam(parameters, lr=lr)
    for i in range(epochs):
        model.train()
        sum_loss = 0.0
        total = 0
        for x, y, l in train_dl:
            x = x.long()
            y = y.long()
            y_pred = model(x, l)
            optimizer.zero_grad()
            loss = F.cross_entropy(y_pred, y)
            loss.backward()
            optimizer.step()
            sum_loss += loss.item()*y.shape[0]
            total += y.shape[0]
        val_loss, val_acc, val_rmse = validation_metrics(model, val_dl)
        if i % 5 == 1:
            print("train loss %.3f, val loss %.3f, val accuracy %.3f, and val rmse %.3f" % (sum_loss/total, val_loss, val_acc, val_rmse))


In [21]:
a = torch.randn(5, 7, dtype=torch.double)
a_int = a.abs().long()

In [22]:
a_int

tensor([[0, 1, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0, 0],
        [1, 1, 0, 0, 1, 2, 0],
        [0, 1, 0, 0, 0, 1, 1],
        [0, 1, 0, 0, 0, 1, 1]])

In [17]:
embed(a_int)

tensor([[[-0.7371, -0.8117,  1.8271,  ..., -1.8414,  0.8111,  0.5779],
         [-0.7371, -0.8117,  1.8271,  ..., -1.8414,  0.8111,  0.5779],
         [-2.0179,  0.4484,  0.6995,  ..., -0.0887,  0.3736,  1.8991],
         ...,
         [-2.0179,  0.4484,  0.6995,  ..., -0.0887,  0.3736,  1.8991],
         [-0.7371, -0.8117,  1.8271,  ..., -1.8414,  0.8111,  0.5779],
         [-0.7371, -0.8117,  1.8271,  ..., -1.8414,  0.8111,  0.5779]],

        [[-0.7371, -0.8117,  1.8271,  ..., -1.8414,  0.8111,  0.5779],
         [-0.7371, -0.8117,  1.8271,  ..., -1.8414,  0.8111,  0.5779],
         [-0.7371, -0.8117,  1.8271,  ..., -1.8414,  0.8111,  0.5779],
         ...,
         [-0.7371, -0.8117,  1.8271,  ..., -1.8414,  0.8111,  0.5779],
         [-0.7371, -0.8117,  1.8271,  ..., -1.8414,  0.8111,  0.5779],
         [-0.7371, -0.8117,  1.8271,  ..., -1.8414,  0.8111,  0.5779]],

        [[-0.7371, -0.8117,  1.8271,  ..., -1.8414,  0.8111,  0.5779],
         [-2.0179,  0.4484,  0.6995,  ..., -0